# Generated by Django 5.1.3 on 2024-12-10 14:50

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('immagine', models.ImageField(upload_to=shop.models.rename_brand_image)),
            ],
        ),
        migrations.CreateModel(
            name='Dettagli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condizione', models.CharField(choices=[('new', 'Nuovo'), ('used', 'Usato'), ('refurbished', 'Ricondizionato')], max_length=15)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantita', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Dettagli Prodotto',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisto', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente', to=settings.AUTH_USER_MODEL)),
                ('dettagli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotto_dettaglio', to='shop.dettagli')),
            ],
            options={
                'verbose_name_plural': 'Comande',
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('immagine', models.ImageField(upload_to=shop.models.rename_product_image)),
                ('data_pub', models.DateTimeField(auto_now_add=True)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modello', to='shop.brand')),
            ],
            options={
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.AddField(
            model_name='dettagli',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotto', to='shop.prodotto'),
        ),
        migrations.AlterUniqueTogether(
            name='dettagli',
            unique_together={('prodotto', 'condizione')},
        ),
    ]
