# Generated by Django 5.1.3 on 2024-12-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='brand_imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantita', models.PositiveIntegerField(default=0)),
                ('condizione', models.CharField(choices=[('new', 'Nuovo'), ('used', 'Usato'), ('refurbished', 'Ricondizionato')], max_length=20)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='prodotti_imgs/')),
                ('data_pub', models.DateTimeField(auto_now_add=True)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modello', to='shop.brand')),
            ],
            options={
                'verbose_name_plural': 'Prodotti',
            },
        ),
    ]
