# Generated by Django 5.1.3 on 2024-12-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_brand_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='immagine',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
