# Generated by Django 5.1.3 on 2024-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_dettagli_prodotto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dettagli',
            options={'verbose_name_plural': 'Quantità Prodotto'},
        ),
        migrations.AlterField(
            model_name='dettagli',
            name='condizione',
            field=models.CharField(choices=[('new', 'Nuovo'), ('used', 'Usato'), ('refurbished', 'Ricondizionato')], max_length=15),
        ),
    ]
