# Generated by Django 5.1.3 on 2024-12-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_dettagli_memoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dettagli',
            unique_together=set(),
        ),
    ]
