# Generated by Django 5.1.3 on 2024-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_dettagli_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='attiva',
            field=models.BooleanField(default=True),
        ),
    ]
