# Generated by Django 5.1.3 on 2024-12-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_comanda_attiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='attiva',
        ),
        migrations.AddField(
            model_name='comanda',
            name='completata',
            field=models.BooleanField(default=False),
        ),
    ]
