# Generated by Django 5.1.3 on 2024-12-10 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoria', models.PositiveIntegerField(help_text='Capacità di memoria in GB')),
                ('condizione', models.CharField(choices=[('excellent', 'Eccellente'), ('good', 'Buono'), ('fair', 'Discreto'), ('damaged', 'Danneggiato'), ('not_working', 'Non funzionante')], max_length=20)),
                ('schermo_rotto', models.BooleanField(default=False, help_text='Lo schermo è rotto?')),
                ('back_rotto', models.BooleanField(default=False, help_text='Ha il vetro posteriore rotto?')),
                ('stato_batteria', models.IntegerField(help_text='Qual è lo stato batteria?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('bloccato', models.BooleanField(default=False, help_text='Il telefono è bloccato dalla casa produttrice?')),
                ('commento', models.CharField(blank=True, help_text='Aggiungi ulteriori commenti sullo stato del dispositivo', max_length=200, null=True)),
                ('valore', models.DecimalField(blank=True, decimal_places=2, help_text='Valore stimato del dispositivo', max_digits=10, null=True)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.prodotto')),
            ],
        ),
    ]
