# Generated by Django 5.1.3 on 2024-12-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_alter_valutazione_options_valutazione_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valutazione',
            name='brand',
        ),
    ]
