# Generated by Django 5.1.3 on 2024-12-11 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_alter_valutazione_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valutazione',
            name='back_rotto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='valutazione',
            name='schermo_rotto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='valutazione',
            name='stato_batteria',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
