# Generated by Django 5.1.3 on 2024-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_alter_valutazione_back_rotto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valutazione',
            name='attiva',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='valutazione',
            name='memoria',
            field=models.PositiveIntegerField(choices=[(64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1 TB')]),
        ),
    ]
