# Generated by Django 5.1.3 on 2024-12-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_valutazione_attiva_alter_valutazione_memoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valutazione',
            name='attiva',
        ),
        migrations.AddField(
            model_name='valutazione',
            name='completata',
            field=models.BooleanField(default=False),
        ),
    ]
